artifacts_root: artifacts

data_ingestion:
  dir: artifacts/data_ingestion
  train_data: artifacts/data_ingestion/train.csv
  test_data:  artifacts/data_ingestion/test.csv
  raw_data:   artifacts/data_ingestion/raw.csv

data_transformation:
  dir: artifacts/data_transformation
  train_data: artifacts/data_ingestion/train.csv
  test_data:  artifacts/data_ingestion/test.csv
  preproecss_obj: artifacts/data_transformation/preprocesser.pkl
  train_arr: artifacts/data_transformation/train_arr.npy
  test_arr: artifacts/data_transformation/test_arr.npy


model_trainer:
  dir: artifacts/model_trainer
  train_arr: artifacts/data_transformation/train_arr.npy
  test_arr: artifacts/data_transformation/test_arr.npy
  model: artifacts/model_trainer/model.pkl 



model_eval:
  dir: artifacts/model_eval
  test_arr: artifacts/data_transformation/test_arr.npy
  model: artifacts/model_trainer/model.pkl
  metrics: artifacts/model_eval/metrics.json
  
