artifact_location: /workspaces/GemStone-Price-Prediction/MLFLOW_TRACKING_URI=https:/dagshub.com/arpanchakraborty23/GemStone-Price-Prediction.mlflow/0
creation_time: 1714415852470
experiment_id: '0'
last_update_time: 1714415852470
lifecycle_stage: active
name: Default
